<Home>:
    orientation: 'vertical'
    spacing: 10
    padding: 50
    Label:
        id: nome_usuario
        text: 'user name:'
        size_hint_y: None
        height: 30
    TextInput:
        id: user_name
    Label:
        id: senha
        text: 'Senha:'
        size_hint_y: None
        height: 30
    TextInput:
        id: pass_w
    Button:
        id: salvar
        text: 'Salvar'
    Button:
        id: cancelar
        text: 'Cancelar'
